library/urls.py
from django.contrib import admin
from django.urls import path
from web import views
from web import account

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('manager/',views.manager),
    path('reader/',views.reader),
    path('manager/card/',views.manager_card),
    path('manager/card/add/',views.manager_card_add),
    path('manager/card/delete/',views.manager_card_delete),
    path('book/add/',views.book_add),
    path('book/add/suc/',views.book_add_suc),
    path('book/list/',views.book_list),
    path('book/list2/',views.book_list2),
    path('login/',account.login),
    path('logout/',account.logout),
    path('book/borrow/',views.book_borrow),
    path('book/borrow2/',views.book_borrow2),
    path('book/reborrow/',views.book_reborrow),
    path('book/reborrow2/',views.book_reborrow2),
    path('book/return/',views.book_return),
    path('book/return2/',views.book_return2),
    path('book/modify/',views.book_modify),
    path('book/modify2/',views.book_modify2),
    path('register/',account.register),
    ]

web/models.py
from distutils.command.upload import upload
from unittest.util import _MAX_LENGTH
from django.db import models
from django.forms import CharField, IntegerField

# Create your models here.

# 设置管理员表，保存管理员信息
class manager(models.Model):
    id=models.CharField(verbose_name="ID",max_length=32,primary_key=True)
    password=models.CharField(verbose_name="密码",max_length=32)
    name=models.CharField(verbose_name="姓名",max_length=32)
    contact=models.CharField(verbose_name="联系方式",max_length=20)

# 设置图书信息，存储图书信息
class book(models.Model):
    bno=models.CharField(verbose_name="图书编号",max_length=32,primary_key=True)
    type=models.CharField(verbose_name="类别",max_length=20)
    title=models.CharField(verbose_name="书名",max_length=32)
    publisher=models.CharField(verbose_name="出版社",max_length=32)
    author=models.CharField(verbose_name="作者",max_length=32)
    year=models.IntegerField(verbose_name="年份")
    price=models.DecimalField(verbose_name="价格",max_digits=8,decimal_places=2)
    total=models.IntegerField(verbose_name="总藏书量")
    stock=models.IntegerField(verbose_name="当前库存")

# 借书证表，用于管理借书证

class card(models.Model):
    cno=models.CharField(verbose_name="卡号",max_length=32,primary_key=True)
    name=models.CharField(verbose_name="姓名",max_length=32)
    department=models.CharField(verbose_name="部门",max_length=32)
    password=models.CharField(verbose_name="密码",max_length=32)
    type_choices=(
        (1,'学生'),
        (2,'教师'),
    )
    type=models.SmallIntegerField(verbose_name="类别",choices=type_choices)


# 文件上传图书入库
class newbooks(models.Model):
    file=models.FileField(verbose_name="上传")

class borrow_list(models.Model):
    book=models.ForeignKey(to="book",to_field="bno",verbose_name="书号",on_delete=models.CASCADE)
    card=models.ForeignKey(to="card",to_field="cno",verbose_name="卡号",on_delete=models.CASCADE)
    borrow_time=models.DateField(verbose_name="借期")
    return_time=models.DateField(verbose_name="预计还期")
    manager=models.ForeignKey(to="manager",to_field="id",verbose_name="经手人",null=True, blank=True, on_delete=models.SET_NULL)

web/templates/book_add_suc.html
{% extends 'layout1.html' %} 

{% block title %} 
<title>入库成功</title>
{% endblock %}

{% block content %} 
<div class="container">
    <div class="alert alert-info" role="alert">
        <div style="margin-bottom:60px" ><center> </center></div>
         <div style="margin-bottom:60px" ><center><h1><strong>入 库 成 功</strong></h1></center></div>
        <div style="margin-bottom:40px"><center><a class="btn btn-default btn-lg" href="/book/add/" role="button">继续入库</a></center></div>
    </div>
</div>
{% endblock %}

web/templates/book_borrow.html
{% extends 'layout1.html' %}

{% block title %}
<title>借阅图书</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">借阅图书</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>卡号</label>
                    <input type="text" name="nid" class="form-control" value="{{ nid }}" id="id_cno">
                    <!-- <span style="color: red;"></span> -->
                </div>
                <div class="form-group">
                    <label>书号</label>
                    {{ form.bno }}
                    <!-- <span style="color: red;">{{ form.bno.errors.0 }}</span> -->
                </div>
                <div class="form-group">
                    <label>借期(YYYY-MM-DD)</label>
                    {{ form.borrow_date }}
                    <!-- <span style="color: red;">{{ form.borrow_date.errors.0 }}</span> -->
                </div>
                <div class="form-group">
                    <label>预计还期(YYYY-MM-DD)</label>
                    {{ form.return_date }}
                    <!-- <span style="color: red;">{{ form.return_date.errors.0 }}</span> -->
                </div>
                <center>
                    <button type="submit" class="btn btn-primary" style="margin-right: 20px;">借阅图书</button>
                    <a href="/book/modify/" class="btn btn-primary">返回</a>
                </center>
            </form>
            <span style="color: red;">{{ form.errors }}</span>
        </div>
    </div>
    <center><span style="color:red;"><h4>{{error_msg}}{{date}}</h4></span></center>
    <center><span style="color:green;"><h4>{{suc_msg}}</h4></span></center>
</div>
{% endblock %}

web/templates/book_borrow2.html
{% extends 'layout2.html' %}

{% block title %}
<title>借阅图书</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">借阅图书</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>卡号</label>
                    <input type="text" name="nid" class="form-control" value="{{ nid }}" id="id_cno">
                    <!-- <span style="color: red;"></span> -->
                </div>
                <div class="form-group">
                    <label>书号</label>
                    {{ form.bno }}
                    <!-- <span style="color: red;">{{ form.bno.errors.0 }}</span> -->
                </div>
                <div class="form-group">
                    <label>借期(YYYY-MM-DD)</label>
                    {{ form.borrow_date }}
                    <!-- <span style="color: red;">{{ form.borrow_date.errors.0 }}</span> -->
                </div>
                <div class="form-group">
                    <label>预计还期(YYYY-MM-DD)</label>
                    {{ form.return_date }}
                    <!-- <span style="color: red;">{{ form.return_date.errors.0 }}</span> -->
                </div>
                <center>
                    <button type="submit" class="btn btn-primary" style="margin-right: 20px;">借阅图书</button>
                    <a href="/book/modify2/" class="btn btn-primary">返回</a>
                </center>
            </form>
            <span style="color: red;">{{ form.errors }}</span>
        </div>
    </div>
    <center><span style="color:red;"><h4>{{error_msg}}{{date}}</h4></span></center>
    <center><span style="color:green;"><h4>{{suc_msg}}</h4></span></center>
</div>
{% endblock %}

web/templates/book_list2.html
{% extends 'layout2.html' %}

{% block title %}
<title>图书查询</title>
{% endblock %}

{% block content %}

<div class="container">
    <h1><strong>
        <center>图书查询</center>
    </strong></h1>
    <div style="margin-bottom:30px"> </div>
    <form method='GET'>
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-2">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn default" type="button">书号</button>
                    </span>
                   <input type="text" class="form-control" name="b" placeholder=" " value="{{ search_b }}">
                </div><!-- /input-group -->
            </div>
            <div class="col-lg-2">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn default" type="button">书名</button>
                    </span>
                   <input type="text" class="form-control" name="t" placeholder=" " value="{{ search_t }}">
                </div><!-- /input-group -->
            </div>
            <div class="col-lg-2">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn default" type="button">作者</button>
                    </span>
                    <input type="text" class="form-control" name="a" placeholder=" " value="{{ search_a }}">
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
            <div class="col-lg-2">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn default" type="button">出版社</button>
                    </span>
                    <input type="text" class="form-control" name="p" placeholder=" " value="{{ search_p }}">
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
            <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search"
                aria-hidden="true"></span>  搜 索</button>
        </div><!-- /.row -->
        
            
 
        <div style="margin-bottom:40px"> </div>


    </form><!-- 表格面板 -->
       


    <div style="margin-bottom:20px"> </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
            图书列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>书号</th>
                    <th>类别</th>
                    <th>书名</th>
                    <th>出版社</th>
                    <th>作者</th>
                    <th>年份</th>
                    <th>价格</th>
                    <th>总藏书量</th>
                    <th>库存</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in queryset %}
                <tr>
                    <th>{{ obj.bno }}</th>
                    <td>{{ obj.type }}</td>
                    <td>{{ obj.title }}</td>
                    <td>{{ obj.publisher }}</td>
                    <td>{{ obj.author }}</td>
                    <td>{{ obj.year}}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.total }}</td>
                    <td>{{ obj.stock }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
</div>




{% endblock %}

web/templates/book_reborrow.html
{% extends 'layout1.html' %}

{% block title %}
<title>借阅图书</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">续借图书</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>卡号</label>
                    <input type="text" name="nid" class="form-control" value="{{ nid }}" id="id_cno">
                    <!-- <span style="color: red;"></span> -->
                </div>
                <div class="form-group">
                    <label>书号</label>
                    {{ form.bno }}
                    <!-- <span style="color: red;">{{ form.bno.errors.0 }}</span> -->
                </div>
                <div class="form-group">
                    <label>预计还期(YYYY-MM-DD)</label>
                    {{ form.return_date }}
                    <!-- <span style="color: red;">{{ form.return_date.errors.0 }}</span> -->
                </div>
                <center>
                    <button type="submit" class="btn btn-primary" style="margin-right: 20px;">续借图书</button>
                    <a href="/book/modify/" class="btn btn-primary">返回</a>
                </center>
            </form>
            <span style="color: red;">{{ form.errors }}</span>
        </div>
    </div>
    <center><span style="color:red;"><h4>{{error_msg}}{{date}}</h4></span></center>
    <center><span style="color:green;"><h4>{{suc_msg}}</h4></span></center>
</div>
{% endblock %}

web/templates/book_reborrow2.html
{% extends 'layout2.html' %}

{% block title %}
<title>借阅图书</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">续借图书</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>卡号</label>
                    <input type="text" name="nid" class="form-control" value="{{ nid }}" id="id_cno">
                    <!-- <span style="color: red;"></span> -->
                </div>
                <div class="form-group">
                    <label>书号</label>
                    {{ form.bno }}
                    <!-- <span style="color: red;">{{ form.bno.errors.0 }}</span> -->
                </div>
                <div class="form-group">
                    <label>预计还期(YYYY-MM-DD)</label>
                    {{ form.return_date }}
                    <!-- <span style="color: red;">{{ form.return_date.errors.0 }}</span> -->
                </div>
                <center>
                    <button type="submit" class="btn btn-primary" style="margin-right: 20px;">续借图书</button>
                    <a href="/book/modify2/" class="btn btn-primary">返回</a>
                </center>
            </form>
            <span style="color: red;">{{ form.errors }}</span>
        </div>
    </div>
    <center><span style="color:red;"><h4>{{error_msg}}{{date}}</h4></span></center>
    <center><span style="color:green;"><h4>{{suc_msg}}</h4></span></center>
</div>
{% endblock %}

web/templates/book_return.html
{% extends 'layout1.html' %}

{% block title %}
<title>归还图书</title>
{% endblock %}


{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">归还图书</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>卡号</label>
                    <input type="text" name="cno" class="form-control" value={{ nid }}>
                    <!-- <span style="color: red;"></span> -->
                </div>
                <div class="form-group">
                    <label>书号</label>
                    {{ form.bno }}
                    <!-- <span style="color: red;">{{ form.bno.errors.0 }}</span> -->
                </div>
                <center>
                    <button type="submit" class="btn btn-primary" style="margin-right: 20px;">归还图书</button>
                    <a href="/book/modify/" class="btn btn-primary">返回</a>
                </center>
            </form>
            <span style="color: red;">{{ form.errors }}</span>
        </div>
    </div>
    <center><span style="color:red;"><h4>{{error_msg}}{{date}}</h4></span></center>
    <center><span style="color:green;"><h4>{{suc_msg}}</h4></span></center>
</div>

{% endblock %}

web/templates/book_return2.html
{% extends 'layout2.html' %}

{% block title %}
<title>归还图书</title>
{% endblock %}


{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">归还图书</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>卡号</label>
                    <input type="text" name="cno" class="form-control" value={{ nid }}>
                    <!-- <span style="color: red;"></span> -->
                </div>
                <div class="form-group">
                    <label>书号</label>
                    {{ form.bno }}
                    <!-- <span style="color: red;">{{ form.bno.errors.0 }}</span> -->
                </div>
                <center>
                    <button type="submit" class="btn btn-primary" style="margin-right: 20px;">归还图书</button>
                    <a href="/book/modify2/" class="btn btn-primary">返回</a>
                </center>
            </form>
            <span style="color: red;">{{ form.errors }}</span>
        </div>
    </div>
    <center><span style="color:red;"><h4>{{error_msg}}{{date}}</h4></span></center>
    <center><span style="color:green;"><h4>{{suc_msg}}</h4></span></center>
</div>

{% endblock %}

web/templates/layout1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %} {% endblock %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
</head>

<body>
    <!-- Brand and toggle get grouped for better mobile display -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" style="padding: 0px 30px;">
            <div>
                <a class="navbar-brand" href="#">图书管理系统</a>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">{{ name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">                          
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        
        </div>  
         
    </nav>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container" style="margin:0px; padding: 0px;">
        <div class="row" style="margin: 0px;">
            <div class="col-sm-3 col-md-2" style="padding: 70px 0px;background-color: rgb(245,245,245);height: 100vh; position: fixed; top: 0; left: 0; bottom: 0; width: 200px; z-index: 999;">
                <div class="sidebar">
                    
                    <ul class="nav navbar-sidebar">
                        <li><a href="/book/list/" style="padding: 15px 30px;"><span class="glyphicon glyphicon-search" aria-hidden="true" style="margin-right: 10px;"></span>图书查询</a></li>
                        <li><a href="/book/add/" style="padding: 15px 30px;"><span class="glyphicon glyphicon-download-alt" aria-hidden="true" style="margin-right: 10px;"></span>图书入库</a></li>
                        <li><a href="/book/modify/" style="padding: 15px 30px;"><span class="glyphicon glyphicon-tasks" aria-hidden="true" style="margin-right: 10px;"></span>借/还图书</a></li>
                        <li><a href="/manager/card/" style="padding: 15px 30px;"><span class="glyphicon glyphicon-folder-open" aria-hidden="true" style="margin-right: 10px;"></span>借书证管理</a></li>
                    </ul>
                    
                </div>
            </div>
            <div class="col-sm-9 col-md-10" style="padding: 100px 0px; margin-left: 200px;">
                <div class="main">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
    
    

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
</body>

</html>

web/templates/layout2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %} {% endblock %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
</head>

<body>
    <!-- Brand and toggle get grouped for better mobile display -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" style="padding: 0px 30px;">
            <div>
                <a class="navbar-brand" href="#">图书管理系统</a>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">{{ name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">                          
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        
        </div>  
         
    </nav>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="container" style="margin:0px; padding: 0px;">
        <div class="row" style="margin: 0px;">
            <div class="col-sm-3 col-md-2" style="padding: 70px 0px;background-color: rgb(245,245,245);height: 100vh;">
                <div class="sidebar">
                    <ul class="nav navbar-sidebar">
                        <li><a href="/book/list2/" style="padding: 15px 30px;"><span class="glyphicon glyphicon-search" aria-hidden="true" style="margin-right: 10px;"></span>图书查询</a></li>
                        <li><a href="/book/modify2/" style="padding: 15px 30px;"><span class="glyphicon glyphicon-tasks" aria-hidden="true" style="margin-right: 10px;"></span>借/还图书</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-9 col-md-10" style="padding: 100px 0px;">
                <div class="main">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
    

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
</body>

</html>

web/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %} {% endblock %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
</head>

    <style>
        *{
    /* 初始化 */
    margin: 0;
    padding: 0;
}
        .container{
    /* 相对定位 */
    position: relative;
    z-index: 1;
    background-color: #fff;
    border-radius: 15px;
    /* 弹性布局 垂直排列 */
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 350px;
    height: 400px;
    /* 阴影 */
    box-shadow: 0 5px 20px rgba(0,0,0,0.1);
}

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
        body {
    /* 100%窗口高度 */
    height: 100vh;
    /* 弹性布局 居中 */
    display: flex;
    justify-content: center;
    align-items: center;
    /* 渐变背景 */
    background: linear-gradient(200deg,#e3c5eb,#a9c1ed);
    /* 溢出隐藏 */
    overflow: hidden;   
        }
        ul li{
    position: absolute;
    border: 1px solid #fff;
    background-color: #fff;
    width: 30px;
    height: 30px;
    list-style: none;
    opacity: 0;
}
        .square li{
    top: 40vh;
    left: 60vw;
    /* 执行动画：动画名 时长 线性的 无限次播放 */
    animation: square 10s linear infinite;
}
.square li:nth-child(2){
    top: 80vh;
    left: 10vw;
    /* 设置动画延迟时间 */
    animation-delay: 2s;
}
.square li:nth-child(3){
    top: 80vh;
    left: 85vw;
    /* 设置动画延迟时间 */
    animation-delay: 4s;
}
.square li:nth-child(4){
    top: 10vh;
    left: 70vw;
    /* 设置动画延迟时间 */
    animation-delay: 6s;
}
.square li:nth-child(5){
    top: 10vh;
    left: 10vw;
    /* 设置动画延迟时间 */
    animation-delay: 8s;
}
.circle li{
    bottom: 0;
    left: 15vw;
    /* 执行动画 */
    animation: circle 10s linear infinite;
}
.circle li:nth-child(2){
    left: 35vw;
    /* 设置动画延迟时间 */
    animation-delay: 2s;
}
.circle li:nth-child(3){
    left: 55vw;
    /* 设置动画延迟时间 */
    animation-delay: 6s;
}
.circle li:nth-child(4){
    left: 75vw;
    /* 设置动画延迟时间 */
    animation-delay: 4s;
}
.circle li:nth-child(5){
    left: 90vw;
    /* 设置动画延迟时间 */
    animation-delay: 8s;
}

/* 定义动画 */
@keyframes square {
    0%{
        transform: scale(0) rotateY(0deg);
        opacity: 1;
    }
    100%{
        transform: scale(5) rotateY(1000deg);
        opacity: 0;
    }
}
@keyframes circle {
    0%{
        transform: scale(0) rotateY(0deg);
        opacity: 1;
        bottom: 0;
        border-radius: 0;
    }
    100%{
        transform: scale(5) rotateY(1000deg);
        opacity: 0;
        bottom: 90vh;
        border-radius: 50%;
    }
}
    </style>
</head>
<body>
<div class="main">

<div class="container" >
    <center><h3 style="margin-top: 50px;">欢迎进入图书管理系统</h3></center>
    <h2>用户登录</h2>
    <div style="margin-bottom:20px"> </div>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-btn">
                <button class="btn btn-defaut" type="button">账户</button>
            </span>
            {{ form.id }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div style="margin-bottom:20px"> </div>
        <div class="input-group">
            <span class="input-group-btn">
                <button class="btn btn-defaut" type="button">密码</button>
            </span>
            {{ form.password }}
            <center><span style="color: red;">{{ form.password.errors.0 }}</span></center>
        </div>
        <div style="margin-bottom:20px"> </div>
        <center>
        <input type="submit" name="admin_login" value="管理员登录" class="btn btn-primary"  style="float: left;">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="submit" name="reader_login" value="读者登录" class="btn btn-primary"style="float: right;">
        </center>   
        <div style="margin-bottom:30px"> </div>
        <div style="text-align:center;">
            <span>没有账号？<a href="/register/">去注册</a></span>
        </div>
        
        <div style="margin-bottom:10px"> </div>
    </form>
</div>
<div class="square">
    <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>
<div class="circle">
    <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>
</body>
</html>

web/templates/manager_card.html
{% extends 'layout1.html' %}

{% block title %}
<title>借书证管理</title>
{% endblock %}

{% block content %}

<div class="container">
    <h1><strong>
        <center>借书证管理</center>
    </strong></h1>
    <form method='POST'>
        {% csrf_token %}
        <div style="margin-bottom:40px"> </div>
        <div class="row">
            <div class="col-lg-9">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn btn-defaut" type="button">借书证号</button>
                    </span>
                    <input type="text" class="form-control form-control" name="nid" value="{{ nid }}"
                        placeholder="{{ nid }}">
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
            <div class="col-lg-1">
            <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search"
                    aria-hidden="true"></span> 搜 索</button></div>
            <div class="col-lg-2">
                <!--添加按钮 -->
                <a class="btn btn-primary" href="/manager/card/add/">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    新建借书证
                </a>
            </div>
        </div><!-- /.row -->
        <div style="margin-bottom:20px"> </div>
        <div>
        <center><span style="color:red;"><h4>{{error_msg}}</h4></span></center>

            <!-- 表格面板 -->
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
                    借书证列表
                </div>

                <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>借书证</th>
                            <th>姓名</th>
                            <th>单位</th>
                            <th>密码</th>
                            <th>类别</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in queryset %}
                        <tr>
                            <th>{{ obj.cno }}</th>
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.department }}</td>
                            <td>{{ obj.password }}</td>
                            <td>{{ obj.get_type_display }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit/">编辑</a> 
                                <a class="btn btn-danger btn-xs" href="/manager/card/delete/?nid={{ obj.cno }}">删除</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endblock %}

web/templates/reader.html
{% extends 'layout2.html' %}

{% block content %}
{% endblock %}